In [1]:
import gym
import pandas as pd
import numpy as np
from gym import envs
list(envs.registry.all())
np.set_printoptions(suppress=True)

[EnvSpec(Copy-v0),
 EnvSpec(RepeatCopy-v0),
 EnvSpec(ReversedAddition-v0),
 EnvSpec(ReversedAddition3-v0),
 EnvSpec(DuplicatedInput-v0),
 EnvSpec(Reverse-v0),
 EnvSpec(CartPole-v0),
 EnvSpec(CartPole-v1),
 EnvSpec(MountainCar-v0),
 EnvSpec(MountainCarContinuous-v0),
 EnvSpec(Pendulum-v0),
 EnvSpec(Acrobot-v1),
 EnvSpec(LunarLander-v2),
 EnvSpec(LunarLanderContinuous-v2),
 EnvSpec(BipedalWalker-v2),
 EnvSpec(BipedalWalkerHardcore-v2),
 EnvSpec(CarRacing-v0),
 EnvSpec(Blackjack-v0),
 EnvSpec(KellyCoinflip-v0),
 EnvSpec(KellyCoinflipGeneralized-v0),
 EnvSpec(FrozenLake-v0),
 EnvSpec(FrozenLake8x8-v0),
 EnvSpec(CliffWalking-v0),
 EnvSpec(NChain-v0),
 EnvSpec(Roulette-v0),
 EnvSpec(Taxi-v3),
 EnvSpec(GuessingGame-v0),
 EnvSpec(HotterColder-v0),
 EnvSpec(Reacher-v2),
 EnvSpec(Pusher-v2),
 EnvSpec(Thrower-v2),
 EnvSpec(Striker-v2),
 EnvSpec(InvertedPendulum-v2),
 EnvSpec(InvertedDoublePendulum-v2),
 EnvSpec(HalfCheetah-v2),
 EnvSpec(HalfCheetah-v3),
 EnvSpec(Hopper-v2),
 EnvSpec(Hopper-v3),
 

In [2]:
env = gym.make("Copy-v0")

print(env.observation_space)
print(env.action_space)
print(env.reward_range)


Discrete(6)
Tuple(Discrete(2), Discrete(2), Discrete(5))
(-inf, inf)


In [13]:
observation = env.reset()
print("observation before: ", observation)
env.render()#before


action = env.action_space.sample()
observation, reward, done, info = env.step((1,1,4))
print("observation after: ", observation)
env.render()#1

observation, reward, done, info = env.step((1,1,1))
print("observation after: ", observation)
env.render()#2

observation, reward, done, info = env.step((1,1,1))
print("observation after: ", observation)
env.render()#2

#try it out by manually placing serval letters in the input space

observation before:  2
Total length of input instance: 4, step: 0
Observation Tape    :   CDBB  
Output Tape         :   
Targets             :   CDBB  






observation after:  3
Total length of input instance: 4, step: 1
Observation Tape    :   CDBB  
Output Tape         :   E
Targets             :   CDBB  

Current reward      :   -0.500
Cumulative reward   :   -0.500
Action              :   Tuple(move over input: right,
                              write to the output tape: True,
                              prediction: E)
observation after:  1
Total length of input instance: 4, step: 2
Observation Tape    :   CDBB  
Output Tape         :   CB
Targets             :   CDBB  

Current reward      :   -0.500
Cumulative reward   :   -1.000
Action              :   Tuple(move over input: right,
                              write to the output tape: True,
                              prediction: B)
observation after:  1
Total length of input instance: 4, step: 3
Observation Tape    :

In [55]:
actions = []

for x in range(2):
    for y in range(2):
        for z in range(5):
            actions.append((x,y,z))
states = [i for i in range(6)]
rewards_table = np.zeros(shape=(len(actions),len(states)))
episode = 100000
loop = 10000


def determine_action(observation,rewards_table):
    
    best_action_index = np.argmax(rewards_table[:,observation])
    random_index = np.random.choice(states)    
    final_index = np.random.choice([best_action_index,random_index],p=[0.9,0.1]) #Explore randomly, but sometime exploit the best action 
    actions[final_index]

    return actions[final_index]

for e in range(episode):
    observation = env.reset()
    done = False
    for t in range(loop):

        action = determine_action(observation,rewards_table)
        new_observation, reward, done, info = env.step(action)
        #print(observation)
        action_index = actions.index(action)
        observation_index = states.index(observation)
        
        rewards_table[action_index][observation_index] += reward
        observation = new_observation
        #print(rewards_table)
        #env.render()
        if done:
            break

print(rewards_table)

[[    0.     -2.     -6.     -3.     -4.    -18. ]
 [   -1.     -4.     -3.     -5.     -3.    -18. ]
 [   -1.     -2.     -3.     -4.     -4.    -18. ]
 [   -2.     -5.     -4.     -3.     -1.    -19. ]
 [   -3.     -4.     -3.     -2.     -2.    -18. ]
 [15370.5  -298.5  -257.   -284.   -276.   -594.5]
 [    0.  15324.5    -0.5    -0.5    -0.5   -17.5]
 [    0.      0.  15110.5    -0.5    -0.5   -17.5]
 [    0.      0.      0.  15378.5    -0.5   -17.5]
 [    0.      0.      0.      0.  15171.    -17.5]
 [    0.      0.      0.      0.      0.    -18. ]
 [    0.      0.      0.      0.      0.    -18. ]
 [    0.      0.      0.      0.      0.    -17. ]
 [    0.      0.      0.      0.      0.    -17. ]
 [    0.      0.      0.      0.      0.    -17. ]
 [    0.      0.      0.      0.      0.    -17. ]
 [    0.      0.      0.      0.      0.    -17. ]
 [    0.      0.      0.      0.      0.    -17. ]
 [    0.      0.      0.      0.      0.    -17. ]
 [    0.      0.      0.      0

In [126]:
np.argmax(rewards_table[:,5])

10

In [6]:
actions

[(0, 0, 0),
 (0, 0, 1),
 (0, 0, 2),
 (0, 0, 3),
 (0, 0, 4),
 (0, 1, 0),
 (0, 1, 1),
 (0, 1, 2),
 (0, 1, 3),
 (0, 1, 4),
 (1, 0, 0),
 (1, 0, 1),
 (1, 0, 2),
 (1, 0, 3),
 (1, 0, 4),
 (1, 1, 0),
 (1, 1, 1),
 (1, 1, 2),
 (1, 1, 3),
 (1, 1, 4)]

In [54]:
def best_action(observation,rewards_table):
 
    best_action_index = np.argmax(rewards_table[:,observation])
    print(actions[best_action_index])
    return actions[best_action_index]

run = 10
observation = env.reset()
done = False
for n in range(run):
    print(observation)
    action = best_action(observation,rewards_table)
    observation, reward, done, info = env.step(action)
    
    env.render()
    
    print(done)
    if done:
        break
        

2
(0, 1, 2)
Total length of input instance: 3, step: 1
Observation Tape    :   CAC  
Output Tape         :   C
Targets             :   CAC  

Current reward      :   1.000
Cumulative reward   :   1.000
Action              :   Tuple(move over input: left,
                              write to the output tape: True,
                              prediction: C)
False
5
(1, 1, 0)
Total length of input instance: 3, step: 2
Observation Tape    :   CAC  
Output Tape         :   CA
Targets             :   CAC  

Current reward      :   1.000
Cumulative reward   :   2.000
Action              :   Tuple(move over input: right,
                              write to the output tape: True,
                              prediction: A)
False
2
(0, 1, 2)
Total length of input instance: 3, step: 3
Observation Tape    :   CAC  
Output Tape         :   CAC
Targets             :   CAC  

Current reward      :   1.000
Cumulative reward   :   3.000
Action              :   Tuple(move over input: left,
     